(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"index_atlas_", frames: [[0,602,147,130],[0,734,103,176],[0,0,160,600],[149,602,40,94],[105,734,55,91]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.seventeenbottomright = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.seventeenpieleft = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.seventeentable = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.seventeentopleft = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.seventeentoprightcookie = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.whiterectanglefade = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EgQFAy9MAAAhl5MAgLAAAMAAABl5g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.whiterectanglefade, new cjs.Rectangle(-103,-326,206.1,652.2), null);


(lib.tipsrecipesmore = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgnAuQgRgSAAgaQgBgcATgSQASgTAbAAQAXAAAOAOQANANAAAXQAAAIgCACQgCACgJAAIguAAQgEAAgCgCQgCgCAAgDQAAgDACgCQABgCAFAAIAYAAIAGgBQABAAAAAAQAAAAABgBQAAAAAAgBQAAgBAAAAQAAgMgIgIQgIgIgLAAQgOAAgHANQgHAMAAASQAAASAKAOQAJAOAPAAQAJAAAHgCQAGgCAFgEIAFgDQAGgFAEAAQAAAAABAAQAAAAABAAQAAAAABABQABAAAAAAQAAABABAAQAAABAAAAQAAABAAABQAAAAAAABQAAADgCAEQgEAEgFAEQgKAJgKAEQgKAEgMAAQgZAAgRgSg");
	this.shape.setTransform(23.4,30);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AgkA8QgGgCAAgEQAAgFAGgCIADgBQAEgCABgEQABgFAAgIIAAgIIAAgKIAAgHQAAgWgBgHQgBgHgDgBIgFgDQgIgCAAgEQAAgDACgCQACgCAGgCIARgGIAKgBQAGAAACAQIAAACIAAABQAHgKAHgFQAGgGAIABQAIgBAFAGQAFAFAAAJQAAAIgEAFQgDAEgIABIgGgBIgFgEIgCgFQgBgBAAAAQgBgBAAAAQAAgBgBAAQAAAAAAAAQgJAAgDAMQgDALAAAkQAAALABAGQABAFAEABIAEACQAIACAAAFQAAAFgHABQgHADgPAAQgTAAgGgDg");
	this.shape_1.setTransform(12.6,29.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AgrAuQgSgSAAgcQAAgaASgSQASgTAbAAQAbAAARARQAQASAAAaQAAAcgSATQgSATgaAAQgaAAgRgSgAgXgkQgHAKAAARQAAAXALAQQAJARAOAAQAMAAAIgLQAIgKgBgQQAAgXgKgQQgKgRgOAAQgMAAgIAKg");
	this.shape_2.setTransform(0.8,30);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AAuBWQgHgCAAgGQAAgFAIgDIAFgCQACgCABgFIABgWIAAgGIAAg0IgBgeIgPAoQgkBdgHAAQgEAAgHgNQgHgNgRgnIgbg9IgBAvIgBAiIABAWQABAFACACIAFACQAIADAAAFQAAAFgGADQgHACgPAAQgNAAgGgCQgGgDAAgFQAAgEAHgDQAGgDABgCQACgHABgfQACgeAAgnIAAgEIgBgRQgBgEgDgCIgFgDQgIgDAAgEQAAgGAFgBQAGgCASAAIARABIAFABQACABAJAWIAHARIADAJQAeBIABAAQADAAALgaQALgZAPgrIACgIQAFgNAEgEQABgCAFgBIARgBQAQAAAGACQAFABAAAGQAAAFgHACIgDACQgEACgBAEQgBAFAAATIABBFIACAkQABADAGABIACABIAFADQAAAAAAABQABABAAAAQAAABAAAAQAAABAAAAQAAAGgGACQgHACgUAAQgTAAgGgCg");
	this.shape_3.setTransform(-17.2,27.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AhJBKQgWgRgBgdQAAgQAHgMQAHgLARgLIAAgBQgFgFgCgGQgDgGgBgGQAAgTAOgNQAPgMAWAAQAPAAAKAGQAKAGAAAHQAAADgCACQgDACgEAAIgIgDQgKgDgHAAQgKAAgFAGQgGAGAAALQAAAFABADQACAEAEADIAIAFIAHADIADABIABACQAAACgFAFQgFAFgEAAIgFgBIgIgDQgHAGgEAIQgDAJgBALQAAAXAQAPQAPAPAXAAQAUAAAMgKQAMgKAAgRQAAgKgFgGQgFgHgIAAQgJAAgFAGQgFAFAAAHIAAADIAAABIgBABIgDAAQgEAAgCgEQgDgDAAgGQAAgSA1gYIAEgCQANgGAIgIQAHgHAAgJQAAgFgDgDQgDgDgGAAIgFAAIgEABQgBAAgBAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAgFAGgEQAHgEAKAAQANAAAIAIQAIAHAAAMQAAAQgOAMQgNAMgbAKQALAEAGAJQAGAJAAANQAAAJgDAJQgEAJgHAHQgMAMgQAGQgRAGgVAAQglAAgWgRg");
	this.shape_4.setTransform(48.6,-1.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AgIA/IgNgCIgEACIgDABIgDAAIgDgCQgEgDgEgKQgDgKAAgJQAAgEACgDQACgCAEAAQAFAAAGAKIAEAHQAEAFAGADQAHACAGAAQAIAAAFgEQAEgEABgHQAAgKgUgKIgHgDQgTgKgHgHQgGgIgBgLQABgQAKgKQALgKATAAIAHAAIAJACIAFgCIAEgBQAGAAAGAKQAGAJAAALQgBAEgCADQgBACgDAAQgDAAgDgCQgDgDgEgGQgEgHgFgDQgFgDgHAAQgGAAgEAEQgFAEAAAGQAAAGAFAEQAEAEAOAIIACABQAiAQAAATQAAARgNAMQgNALgTAAg");
	this.shape_5.setTransform(25.5,1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AgnAuQgRgSAAgaQgBgcATgSQASgTAbAAQAXAAAOAOQANANAAAXQAAAIgCACQgCACgJAAIguAAQgEAAgCgCQgCgCAAgDQAAgDACgCQABgCAFAAIAYAAIAGgBQABAAAAAAQAAAAABgBQAAAAAAgBQAAAAAAgBQAAgMgIgIQgIgIgLAAQgOAAgHANQgHAMAAASQAAASAKAOQAJAOAPAAQAJAAAHgCQAGgCAFgEIAFgDQAGgFAEAAQAAAAABAAQAAAAABAAQAAAAABABQABAAAAAAQAAABABAAQAAABAAAAQAAABAAABQAAAAAAABQAAADgCAEQgEAEgFAEQgKAJgKAEQgKAEgMAAQgZAAgRgSg");
	this.shape_6.setTransform(13.9,1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("Ag6BTQgHgCAAgFQAAgEAGgCIAGgDQADgDABgJQABgKAAgeIAAgTQgBghgBgKQgBgKgDgBIgFgCQgIgDAAgEQAAgDACgCIAIgEIARgFIAMgCQADAAACABQABACABAFIAAAGIAAACIAAABIAFgEIAFgDQAHgGAHgCQAHgDAGAAQAXAAAOARQAPAQAAAbQAAAcgQATQgRATgYAAQgKAAgEgDQgEgDAAgFQAAgBAAAAQAAgBAAgBQABAAAAgBQAAAAABgBQABgCAEAAIADABIAEAAQANAAAJgLQAIgLAAgSQAAgVgJgNQgJgNgOAAQgLAAgIAHQgHAHAAATIAABNIAAAMQABAFABABQACACAFACIAGABIACACIABAEQAAAEgHACQgHACgSAAQgSAAgFgCg");
	this.shape_7.setTransform(-0.1,3.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AgVBXQgGgCAAgFQAAgFAGgCIADgBQADgCACgEIABgNIAAgIIAAgKIAAgMQAAgUgBgFQgBgFgDgCIgFgCQgIgDAAgEQAAgCACgDIAIgEIASgGIAMgCQAEAAABACQACADAAAFIAAAHIgBAGIgBAeIAAABIAAAeQAAAMABAEQABAGADABIAEABQAHADAAAEQAAAFgGADQgGABgQAAQgSAAgGgCgAgOg9QgGgEAAgHQAAgGAGgFQAGgFAIAAQAHAAAFAFQAGAEAAAHQAAAGgGAFQgGAFgHAAQgIAAgFgFg");
	this.shape_8.setTransform(-10.4,-1.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AgmAuQgRgSAAgaQAAgbASgTQATgTAaAAQAUAAAOALQAOAKAAAOQAAAGgEAEQgEADgGAAQgGAAgEgDQgDgDgFgKQgDgIgFgEQgFgDgHAAQgOAAgHAKQgIALAAATQAAAUALAOQALAOARAAQAGAAAFgCIAKgFIAFgDQAHgFADAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAQAAABAAAAQABAAAAABQAAABAAAAQAAADgDAFIgGAHQgKAJgKAEQgLAEgMAAQgZAAgRgSg");
	this.shape_9.setTransform(-20.1,1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AgnAuQgRgSAAgaQgBgcATgSQASgTAbAAQAXAAAOAOQANANAAAXQAAAIgCACQgCACgJAAIguAAQgEAAgDgCQgBgCAAgDQAAgDABgCQACgCAFAAIAZAAIAFgBQABAAAAAAQAAAAABgBQAAAAAAgBQAAAAAAgBQAAgMgIgIQgIgIgLAAQgOAAgHANQgHAMAAASQAAASAKAOQAJAOAPAAQAJAAAHgCQAGgCAFgEIAFgDQAGgFAEAAQAAAAABAAQAAAAABAAQAAAAABABQABAAAAAAQAAABABAAQAAABAAAAQAAABAAABQAAAAAAABQAAADgDAEQgDAEgFAEQgKAJgKAEQgKAEgMAAQgYAAgSgSg");
	this.shape_10.setTransform(-32.8,1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AAaA9QgLgngJgIQgIgIgMAAQgKAAAAgHQAAgHAIAAQAUAAAKgIQAJgIAAgRQAAgQgKgIQgJgIgTAAQgJAAgEABQgDABgBAEIgCAKIAAAZIAAA1IABAlQAAAIADACIAFADQAHACAAAFQAAAGgGACQgHACgTAAQgTAAgHgCQgHgCAAgGQAAgFAIgDIAFgCQADgCABgPIABg0IgBguQgBgSgCgCQgBgCgHgCQgGgDAAgFQAAgEAEgCQADgCAIAAIAbAAIAYgBIATAAQAbAAAOALQAOALAAAWQAAAQgJAMQgKAMgRAEIAAABQANADAIAIQAHAIAGAUIADAMQAFATAHAAIAEgBIAEAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAQABABAAAAQABAAAAABQAAAAAAABQAAABAAAAQAAAGgHAEQgHADgLAAQgYAAgJgcg");
	this.shape_11.setTransform(-47.7,-1.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AgMAlQgBAAAAAAQgBgBAAAAQAAgBgBAAQAAAAAAgBIADgEIACgEIAHgNIADgJIgBgDIgEgCQgGgCgDgFQgDgEAAgHQAAgIAFgFQAFgFAHAAQAIAAAFAHQAFAHAAALQAAAIgDAIQgDAJgIANIgGAKQgCACgCAAIgGgBg");
	this.shape_12.setTransform(71.1,-21.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AgIA/IgNgCIgEACIgDABIgDAAIgDgCQgEgDgEgKQgDgKAAgJQAAgEACgDQACgCAEAAQAFAAAGAKIAEAHQAEAFAHADQAGACAGAAQAIAAAFgEQAEgEABgHQAAgKgUgKIgHgDQgTgKgHgHQgHgIAAgLQAAgQAMgKQAKgKATAAIAHAAIAJACIAFgCIAEgBQAGAAAGAKQAGAJAAALQAAAEgDADQgBACgDAAQgDAAgDgCQgDgDgDgGQgFgHgFgDQgFgDgHAAQgGAAgEAEQgFAEAAAGQAAAGAFAEQAEAEAOAIIACABQAiAQAAATQAAARgNAMQgNALgUAAg");
	this.shape_13.setTransform(62.1,-28);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("Ag6BTQgHgCABgFQgBgEAGgCIAGgDQADgDABgJQABgKAAgeIAAgTQgBghgBgKQgBgKgDgBIgFgCQgIgDAAgEQAAgDADgCIAHgEIARgFIAMgCQAEAAABABQABACABAFIAAAGIAAACIABABIAEgEIAFgDQAHgGAHgCQAHgDAGAAQAXAAAOARQAPAQAAAbQAAAcgQATQgRATgZAAQgJAAgEgDQgEgDAAgFQAAgBAAAAQAAgBABgBQAAAAAAgBQAAAAABgBQABgCAEAAIADABIAEAAQANAAAJgLQAIgLAAgSQAAgVgJgNQgJgNgNAAQgMAAgIAHQgHAHAAATIAABNIABAMQAAAFABABQACACAGACIAEABIADACIABAEQAAAEgHACQgHACgSAAQgSAAgFgCg");
	this.shape_14.setTransform(49.3,-25.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AgVBXQgGgCAAgFQAAgEAGgDIADgBQADgBACgFIABgNIAAgIIAAgKIAAgNQAAgTgBgFQgBgFgDgCIgFgCQgIgCAAgEQAAgDACgDIAIgDIASgHIAMgCQAEAAABACQACADAAAFIAAAIIgBAFIgBAfIAAAAIAAAeQAAAMABAEQABAFADACIAEABQAHADAAAFQAAAEgGADQgGABgQAAQgSAAgGgCgAgOg9QgGgEAAgGQAAgHAGgFQAGgFAIAAQAHAAAFAEQAGAFAAAHQAAAGgGAFQgGAFgHgBQgIAAgFgEg");
	this.shape_15.setTransform(39,-30.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AgZBXQgHgCAAgGQAAgFAHgCQAGgDABgBQACgDABgUIAAg5IAAggIgBgTQAAgEgDgBIgHgBIgFAAQgIAAgFACQgFACgDAFIgEAIIgDAJIgEADIgEACQgEAAgCgDQgBgEAAgHQAAgQADgKQAEgKAGAAIABAAQAKACAPAAIBHAAQAOAAAKgCIACAAQAGAAADAKQAEAKAAAQQAAAHgCAEQgBADgEAAIgEgCIgEgDIgDgJIgEgIQgEgFgEgCQgFgCgJAAIgFAAIgHABQgCABAAAEIgBATIgBAgIABA5QABAUABADQABABAHADQAHACAAAFQAAAGgHACQgHACgTAAQgSAAgHgCg");
	this.shape_16.setTransform(27.7,-30.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("Ag3BRQgGgFgBgIQAAgGAFgFQAEgEAGAAIAGABIADADIADAEQAEAFACAAQAGAAAHgJQAGgJAAgKQAAgKgJgTIgBgDIgTgqIgLgYQgDgEgGgDIgBAAIgFgEQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgFAGgDQAHgCARAAQASAAAHACQAFACAAAFIAAAEIgDACIgEACQgEACgBACIADAJIAJAZIAKAXQADAGACAAQABAAADgGIAIgTIAJgZIADgLQgBgEgGgEQgHgEAAgDQAAgEAGgCQAFgCAOAAQAPAAAEACQAGACAAAFQAAAFgHABIgFACQgHAEgIAVIgEAJIgPAmQgUAzgMAPQgNAQgSAAQgJAAgFgFg");
	this.shape_17.setTransform(7,-25.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#006E47").s().p("AAWA6IgHgHIgFADQgOAKgPAAQgSAAgLgKQgLgLAAgRQAAgTAOgKQAOgLAZAAQAGAAADACQADACAAAEQAAAGgIAAQgMAAgHAGQgHAGAAALQAAAJAGAGQAGAGALAAQALAAAFgFQAFgGAAgMIAAguQAAgLgEgFQgFgGgIAAQgGAAgFACQgFADgFAGIgCADQgIAJgIAAQgFAAgDgDQgDgDAAgFQAAgMAPgIQAOgIAWAAQANAAAJAEQAKAEAFAGQAEAFACAIQABAHAAARIAAAnIABAKQABAEADAAIAEABQAHACAAAFQAAAFgIAFQgIAFgLAAQgFAAgGgGg");
	this.shape_18.setTransform(-5.6,-28);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#006E47").s().p("AAYBYQgCgCAAgEIAAgGIAAgCIgBgBIgDADIgGAEQgGAFgGADQgIACgIAAQgWAAgOgQQgPgQAAgbQAAgeAQgRQARgTAaAAIAJABQADABACADQACACAAAEQAAAGgIAAIgDAAIgDAAQgOAAgHALQgJAKABATQgBAVAKAMQAIANAOAAQAMAAAHgHQAHgHAAgNIAAgiIAAg3QAAgJgCgDQgCgDgEgCIgDgBQgIgCAAgEQABgEACgCIANgGIANgEIAMgBQADAAACACQACADAAAFIAAAGIgCBLIABAzQACALACACIAIADQAGABAAAFQAAAFgSAGIgMADIgJABQgEAAgBgCg");
	this.shape_19.setTransform(-19,-30.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#006E47").s().p("AgVBXQgGgCAAgFQAAgEAGgDIADgBQADgBACgFIABgNIAAgIIAAgKIAAgNQAAgTgBgFQgBgFgDgCIgFgCQgIgCAAgEQAAgDACgDIAIgDIASgHIAMgCQAEAAABACQACADAAAFIAAAIIgBAFIgBAfIAAAAIAAAeQAAAMABAEQABAFADACIAEABQAHADAAAFQAAAEgGADQgGABgQAAQgSAAgGgCgAgOg9QgGgEAAgGQAAgHAGgFQAGgFAIAAQAHAAAFAEQAGAFAAAHQAAAGgGAFQgGAFgHgBQgIAAgFgEg");
	this.shape_20.setTransform(-30.2,-30.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#006E47").s().p("AgUBXQgGgBAAgGQAAgDAFgCIAHgEQACgCABgIIAAgYIAAgTIAAgWIAAgJQAAgfgBgJQgBgJgDgBIgHgDQgIgCAAgEQAAgEADgBQACgDAJgDIAQgEIAMgCQADAAACADQABACAAAFIAAAKQgBArAAAsIABAqQAAAJACABIAHAEQAGACAAAFQAAAFgGACQgGACgQgBQgSAAgGgCg");
	this.shape_21.setTransform(-37.2,-30.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#006E47").s().p("AgrAuQgSgSAAgcQAAgaATgSQARgTAbAAQAaAAASARQAQASAAAaQAAAcgSATQgSATgaAAQgaAAgRgSgAgWgkQgIAKAAARQAAAXAKAQQALARANAAQAMAAAIgLQAHgKAAgQQAAgXgKgQQgKgRgOAAQgMAAgHAKg");
	this.shape_22.setTransform(-47.2,-28);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#006E47").s().p("AAcBWQgIgCABgFQAAgGAHgCIAFgDQACgBACgIIABgdIgBgRIgBgEQgBgDgGgBQgGgBgXAAIgZABQgHABgCACIgBADIgBAJIAAAKIABAdQABAIACABIAFADQAIACgBAGQABAFgHACQgGACgUAAQgTAAgHgCQgHgCAAgFQAAgGAIgCIAFgDQADgCABgPIABgzIgBguQgBgSgBgDQgCgBgGgDQgHgDAAgFQAAgEAGgCQAFgCAWAAQAWAAAFACQAGACgBAEQABAFgIADIgFADQgDABAAAIIgBAkQAAAFAEACQAFACASgBIAJAAIAaAAQAHgBADgCIABgCIABgFIAAgGIgBgdQgCgHgCgBIgFgDQgHgDAAgFQgBgEAHgCQAFgCAWAAQAVAAAGACQAFACAAAEQAAAFgIADIgFADQgDACgBAQIgBAyIABAuQABATACACQABABAGADQAHADAAAFQAAAFgHACQgGACgTAAQgUAAgGgCg");
	this.shape_23.setTransform(-63.3,-30.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.tipsrecipesmore, new cjs.Rectangle(-74.6,-47.3,150.9,91), null);


(lib.sweetinspiration = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AhABBQgHgCAAgGQAAgEAHgCIADgCQADgCACgEQABgFABgKIgBgJIAAgKIAAgNQAAgVgBgGQgBgGgDgCIgGgCQgIgDAAgEQAAgDACgCQADgDAGgCIATgGIAOgCQAEAAABACQABACAAAEIAAAJIABABIABAAIABAAIAAAAIADgDIACgCQAPgOAQAAQAKAAAIAEQAJAEAGAHQAGAIACAKQADAKAAAVIAAARIAAAJIAAAHQAAAJACAEQABAEADACIAEACQAGACAAAEQAAAGgGACQgHACgTAAQgTAAgHgCQgFgCgBgFQAAgFAHgCIAFgCQADgCABgGQABgGAAgOQABgpgGgLQgFgKgOAAQgHAAgGAEQgHAEgDAHQgCAGgCAKIgBAkQAAANABAEQABAEADACIAFACQAGACAAAFQAAAFgGACQgGADgRAAQgVAAgGgDg");
	this.shape.setTransform(57.3,18.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AgvAyQgTgUAAgdQAAgdAUgUQATgUAdAAQAdAAASATQASASAAAdQAAAegTAUQgUAVgcAAQgcAAgTgTgAgYgnQgIALAAASQAAAZALASQALARAPAAQANAAAIgLQAIgKAAgSQAAgZgLgSQgMgRgOAAQgNAAgIAKg");
	this.shape_1.setTransform(42,18.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AgWBeQgHgCAAgGQAAgEAGgCIAEgCQADgCACgEQABgFAAgKIAAgJIAAgKIAAgOQAAgVgBgFQgBgGgDgCIgGgCQgIgDAAgEQAAgDACgCQADgDAGgCIAUgGIANgDQADAAACADQABACAAAGIAAAIIAAAGIgBAhIAAABIAAAgIABASQABAFADACIAFACQAGACAAAFQAAAFgGACQgGADgSAAQgTAAgGgDgAgPhCQgGgEAAgHQAAgIAGgFQAHgGAIAAQAIAAAGAFQAFAFAAAHQAAAIgGAFQgGAFgIAAQgJAAgFgFg");
	this.shape_2.setTransform(30.8,15.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AgGBQQgHgCgFgFQgEgFgCgGQgCgIAAgTIAAhGIgMAAIgEgBIgBgEIAAgDQAAgEAOgNIAFgEIAFgFQAOgMAFABIADAAQABABAAAAQAAAAAAABQABAAAAABQAAAAAAAAIAAAZIAdAAQABAAABABQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABQABAAAAABQAAABAAABIAAADIgBAFQgBAAAAABQgBAAAAAAQgBAAAAAAQgBABgBAAIgbAAIgCAAIgBADIAABCQAAARADADQADAFAIAAIAKgCIAJgDQADAAACACQABABAAAAQAAABABAAQAAABAAABQAAAAAAABQAAAHgLAHQgLAGgPAAQgHAAgGgBg");
	this.shape_3.setTransform(22.5,17.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AAYA+IgHgHIgGADQgQALgQAAQgTAAgMgLQgMgMAAgRQAAgWAPgKQAPgMAcAAQAGAAADACQAEABAAAGQAAAGgJAAQgNABgIAFQgIAHAAALQAAAKAHAHQAHAHAMAAQAMgBAFgGQAGgFAAgOIAAgyQAAgLgFgGQgFgHgJABQgGAAgGADQgFACgGAGIgCADQgIAKgJAAQgGAAgDgDQgDgDAAgGQAAgMAPgIQAQgJAYAAQAOAAAKADQALAEAGAIQAEAFABAIQACAIAAATIAAAqQAAAIABADQABAEADAAIAEABQAIADAAAEQAAAHgIAFQgJAFgMAAQgGAAgGgHg");
	this.shape_4.setTransform(10.9,18.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AgnBBQgHgCAAgGQAAgEAHgCIADgCQAEgCABgEQABgFAAgKIAAgJIAAgKIAAgIQAAgYgBgHQgBgHgDgCIgGgCQgIgDAAgEQAAgDADgCQACgDAGgCIASgGIALgCQAHAAACASIAAACIABABQAGgLAIgFQAHgGAIAAQAJAAAFAGQAGAFAAAJQAAAKgEAFQgFAFgHAAIgHgBIgFgEIgDgFQgBgBAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAQgJAAgEANQgDANAAAnQAAALABAGQABAGAEACIAFABQAIADAAAFQAAAFgHACQgHADgSAAQgUAAgGgDg");
	this.shape_5.setTransform(-1.1,18.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AgWBeQgHgCAAgGQAAgEAGgCIAEgCQADgCACgEQABgFAAgKIAAgJIAAgKIAAgOQAAgVgBgFQgBgGgDgCIgGgCQgIgDAAgEQAAgDACgCQADgDAGgCIAUgGIANgDQADAAACADQABACAAAGIAAAIIAAAGIgBAhIAAABIAAAgIABASQABAFADACIAFACQAGACAAAFQAAAFgGACQgGADgSAAQgTAAgGgDgAgPhCQgGgEAAgHQAAgIAGgFQAHgGAIAAQAIAAAGAFQAFAFAAAHQAAAIgGAFQgGAFgIAAQgJAAgFgFg");
	this.shape_6.setTransform(-10.3,15.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AhABaQgGgCgBgGQABgEAFgCIAHgEQADgCABgLQABgKAAghIAAgVQAAgkgCgKQgBgLgCgBIgHgDQgHgCgBgFQAAgDACgCIAIgEIATgGQAJgDAFAAQADAAABACQADACAAAFIAAAGIAAADIAAABIAFgEIAGgEQAHgGAIgDQAHgCAHAAQAZAAAQASQAPASABAcQgBAfgRAUQgSAVgaAAQgMAAgDgDQgFgEAAgFQAAgDACgCQACgCAEAAIADABIAEAAQAPAAAJgMQAJgMAAgUQAAgWgKgOQgJgOgQAAQgNAAgHAIQgIAHAAAUIAABTIABAOQAAAFACACIAIADIAEACIAEACIABAEQAAAFgJACQgHACgTAAQgTAAgHgCg");
	this.shape_7.setTransform(-22.1,21.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AgJBFIgOgDIgEADIgEAAIgDAAIgDgCQgEgEgEgKQgEgLAAgKQAAgEADgDQACgDADAAQAGAAAHALIAFAIQAEAFAHADQAGADAHAAQAJAAAFgEQAFgEAAgIQAAgLgVgLIgIgDQgUgLgIgHQgHgJAAgMQAAgSAMgLQAMgKATAAIAJAAIAJACIAGgDIAEAAQAHAAAGAKQAGAKAAAMQAAAEgCADQgCADgEAAQgDAAgDgDQgDgCgEgHQgFgIgFgDQgFgDgHAAQgHAAgFAEQgFAEAAAHQAAAGAFAFQAFAFAQAIIABABQAlARAAAVQAAATgOAMQgOAMgWAAg");
	this.shape_8.setTransform(-35.4,18.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AhABBQgHgCAAgGQAAgEAHgCIADgCQADgCACgEQABgFAAgKIAAgJIAAgKIAAgNQAAgVgBgGQgBgGgDgCIgGgCQgIgDAAgEQAAgDACgCQADgDAGgCIATgGIAOgCQAEAAABACQABACAAAEIAAAJIABABIABAAIABAAIAAAAIADgDIACgCQAPgOAQAAQAKAAAIAEQAJAEAGAHQAGAIACAKQADAKAAAVIAAARIAAAJIAAAHQAAAJACAEQABAEADACIAEACQAGACAAAEQAAAGgGACQgHACgTAAQgTAAgHgCQgFgCgBgFQAAgFAHgCIAFgCQADgCABgGQABgGAAgOQABgpgGgLQgFgKgOAAQgHAAgGAEQgHAEgDAHQgCAGgCAKIgBAkQAAANABAEQABAEADACIAFACQAGACAAAFQAAAFgGACQgGADgRAAQgVAAgGgDg");
	this.shape_9.setTransform(-48.9,18.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AgbBdQgHgCAAgGQAAgFAIgDIAGgEQACgBACgRIABg4IgBgyQgBgTgCgCQgBgDgHgCQgHgDAAgFQAAgGAFgBQAHgCAXAAQAXAAAGACQAGABAAAGQgBAFgHADIgHADQgCACgBAOIgBAqIABA/QABAXABACQABACAIADQAGACABAGQgBAGgGACQgIACgVABQgTgBgIgCg");
	this.shape_10.setTransform(-61,15.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AgGBPQgHgCgFgEQgEgEgCgIQgCgHAAgUIAAhGIgMAAIgEgBIgBgDIAAgDQAAgFAOgLIAFgFIAFgEQAOgNAFAAIADACQABAAAAAAQAAAAAAABQABAAAAABQAAAAAAABIAAAZIAdAAQABAAABAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAABABQAAAAAAABQAAABAAAAIAAAEIgBAFQgBAAAAABQgBAAAAAAQgBAAAAAAQgBAAgBAAIgbAAIgCACIgBADIAABAQAAARADAFQADAEAIAAQAEAAAGgCIAJgCQADAAACACQABAAAAAAQAAABABAAQAAABAAABQAAAAAAABQAAAHgLAHQgLAHgPAAQgHgBgGgCg");
	this.shape_11.setTransform(32.5,-13.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AgqAyQgTgUAAgcQAAgeATgUQAUgUAdAAQAZAAAPAPQAPAOAAAZQAAAIgCADQgDACgJAAIgyAAQgFAAgCgCQgCgCAAgEQAAgDACgCQACgCAFAAIAaAAIAHgBQABAAAAAAQAAgBAAAAQABgBAAAAQAAgBAAgBQAAgNgJgIQgIgJgMAAQgQAAgHAOQgIANAAAUQAAAUALAPQAKAPAQAAQAKAAAHgCQAGgDAHgEIAFgEQAGgFAEAAQADAAACACQAAAAABABQAAAAAAABQAAAAABABQAAABAAAAQAAADgEAFIgJAJQgLAKgLAEQgLAEgMAAQgbAAgTgTg");
	this.shape_12.setTransform(20.8,-12.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AgqAyQgTgUAAgcQAAgeATgUQAUgUAdAAQAZAAAPAPQAPAOAAAZQAAAIgCADQgDACgJAAIgyAAQgFAAgCgCQgCgCAAgEQAAgDACgCQACgCAFAAIAaAAIAHgBQABAAAAAAQAAgBAAAAQABgBAAAAQAAgBAAgBQAAgNgJgIQgIgJgMAAQgQAAgHAOQgIANAAAUQAAAUALAPQAKAPAQAAQAKAAAHgCQAGgDAHgEIAFgEQAGgFAEAAQADAAACACQAAAAABABQAAAAAAABQAAAAABABQAAABAAAAQAAADgEAFIgJAJQgLAKgLAEQgLAEgMAAQgbAAgTgTg");
	this.shape_13.setTransform(6.8,-12.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AAHAOIgOgoQgIgTgHgDIgDgCQgIgDAAgFQAAgFAHgCQAHgCAUAAQASAAAGACQAHACgBAFIAAAEIgCADIgFACQgGACABADIACAJIAKAbIAMAZQADAGACAAQABAAADgEIAGgLIAOghQAFgNAAgEIgBgFIgDgDIgEgBQgGgDAAgEQAAgFAGgCQAGgCAQAAQAOAAAGACQAGACgBAFQAAAFgGACIgFACQgGADgMAcIgDAGIgGAMQgdBEgJAAQgJAAgYg2gAhNAHIgEgHIgJgXQgIgWgGgDIgEgCQgIgDABgFQAAgFAGgCQAHgCAVAAQATAAAFACQAHACAAAFIAAAEIgDADIgFACQgFACAAADIADALIAKAZIALAYQAEAHABAAQAEAAAEgIIAEgKIADgEQACgBADAAQADAAACACQACACAAADQAAADgEAIQgNAegHAKQgGAKgEAAQgKAAgag9g");
	this.shape_14.setTransform(-10.8,-12.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AggBfQgPgDgJgGQgFgDgEgLQgDgMAAgOQAAgGACgDQADgDAEgBQAGAAAHANIADAFQAIAOAKAIQAKAGAOAAQANAAALgIQAJgJAAgNQAAgSgmgSIgEgBQgggNgLgMQgKgMAAgSQAAgYARgQQASgPAcABIAPABIASADIAFgDIAFgBQADAAACACIAGAHQAEAJADAIQACAIAAAHQAAAEgCADQgCACgDAAQgHABgHgKIgCgDQgIgKgIgEQgJgEgLgBQgOABgJAGQgIAHAAAMQAAALAHAHQAHAHAcAMIAFACQAYAKAKAJQAHAHAEAJQAEAJAAAKQAAAbgTAPQgTAQggAAQgQAAgPgEg");
	this.shape_15.setTransform(-29.5,-15.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.sweetinspiration, new cjs.Rectangle(-67.3,-33.4,134.6,66.9), null);


(lib.seventeenvidrollover = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B63100").s().p("AnzCoQhFAAgygyQgxgwABhGQgBhFAxgwQAygyBFAAIPnAAQBGAAAwAyQAyAwAABFQAABGgyAwQgwAyhGAAg");
	this.shape.setTransform(0,-64,0.966,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.seventeenvidrollover, new cjs.Rectangle(-64.5,-80.7,129,33.5), null);


(lib.seventeentable_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.seventeentable();
	this.instance.parent = this;
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.seventeentable_1, new cjs.Rectangle(-80,-300,160,600), null);


(lib.seventeenrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("AnzCoQhFAAgygyQgxgwABhGQgBhFAxgwQAygyBFAAIPnAAQBGAAAwAyQAyAwAABFQAABGgyAwQgwAyhGAAg");
	this.shape.setTransform(0,-64,0.966,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.seventeenrectangle, new cjs.Rectangle(-64.5,-80.7,129,33.5), null);


(lib.seventeenpiebottomleft = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.seventeenpieleft();
	this.instance.parent = this;
	this.instance.setTransform(-51.5,-88);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.seventeenpiebottomleft, new cjs.Rectangle(-51.5,-88,103,176), null);


(lib.seventeenordernow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgPAzQgFgDgFgEQgEgFgDgGQgCgHAAgIQAAgHACgGQADgFAEgFQAFgFAFgDQAHgCAHAAQAIAAAFAEQAHADADAEIAAgxIANAAIAABpIgNAAIAAgKQgEAFgGAEQgHADgFAAQgIAAgHgDgAgIgCQgEABgDADIgEAIQgCAEAAAEQAAAFACAEIAEAJIAHAEQAEADAFAAQAFAAAEgCQAEgCADgDIAEgIIACgJQAAgFgCgEIgEgIQgDgDgEgBQgEgDgFAAQgFAAgEADg");
	this.shape.setTransform(35,-65.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgLAhQgHgDgEgFQgEgFgEgFQgCgHAAgIQAAgHACgGQADgGAFgGQAEgEAHgDQAGgCAHAAQAGAAAGACQAHACADAFQAFAEACAHQACAGAAAIIAAABIAAACIgzAAQAAAFACADQABAEADADQADADAEACQAEABADAAQAHAAAEgDQAGgDACgEIAJAHQgFAHgHAEIgHACIgJABQgHAAgGgCgAAUgFIgBgHQgBgEgDgCQgCgDgDgCQgEgBgEAAQgEAAgDABQgEACgDADQgDACgBAEQgCADAAAEIAmAAIAAAAg");
	this.shape_1.setTransform(26.8,-63.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgSAiIAAgzIAAgHIAAgIIAMAAIAAAGIABAGQADgGAEgDIAGgEIAGAAIAFAAIAAANIgGgBQgFAAgDACIgFAEQgDADgBAEIgBAIIAAAig");
	this.shape_2.setTransform(20.7,-63.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgGAxIAAhBIAMAAIAABBgAgFgiQgDgDAAgDQAAgEADgCQACgCADgBQADABADACQADACAAAEQAAAEgDACQgDADgDgBQgDABgCgDg");
	this.shape_3.setTransform(15.9,-65);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgiAzIAAhjIAMAAIAAAKIABAAQADgFAGgDQAHgEAHAAQAHAAAGADQAGACAFAFQAEAFADAGQACAHAAAHQAAAHgCAHQgDAFgEAFQgEAFgHACQgGADgHAAQgHAAgGgDQgGgDgEgGIAAAAIAAAsgAgJglQgEACgDADQgDAEgBAEQgCAEAAAFQAAAFACAEQABAEADADQADADAEACQAEACAFAAQAFAAAEgCIAHgFQADgDABgEIABgJIgBgJQgBgEgDgEQgDgDgEgCQgEgCgFAAQgFAAgEACg");
	this.shape_4.setTransform(9.9,-61.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgOAgQgHgDgFgGIAKgIQACAEAFACQAFADAEAAIAFAAIAEgCIADgDQABAAAAgBQAAAAAAgBQABAAAAgBQAAgBAAAAQAAgFgFgCIgMgFIgHgCIgGgCQgDgCgBgDQgCgDAAgFQAAgFACgEQACgEAEgCQADgDAFgBIAIgBQAHAAAHACQAGAEAEAEIgJAIQgCgDgEgCQgEgDgFAAIgEAAIgEACIgDADIgBAEQAAAEAEACIAKAEIAJADIAHACQADACACAEQACADAAAFQAAAFgDAFQgCAEgEACQgDADgFABQgFABgFAAQgGAAgIgDg");
	this.shape_5.setTransform(2.1,-63.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AARAiIAAgkIgBgHIgCgHIgFgEQgDgCgFAAQgGAAgFAGQgFAGAAAKIAAAiIgNAAIAAgzIgBgHIAAgIIAMAAIABAGIAAAGIAEgGIAFgDIAGgDIAGgBQAGAAAFACQAFACADAEQADAEABAEQACAFAAAGIAAAog");
	this.shape_6.setTransform(-5,-63.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgGAxIAAhBIAMAAIAABBgAgFgiQgDgDAAgDQAAgEADgCQACgCADgBQADABADACQADACAAAEQAAAEgDACQgDADgDgBQgDABgCgDg");
	this.shape_7.setTransform(-10.8,-65);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgDAmQgFgFAAgKIAAgjIgNAAIAAgLIANAAIAAgTIAMAAIAAATIASAAIAAALIgSAAIAAAhQAAAGACADQACACAFAAIAEAAIAEgBIAAALIgFABIgGAAQgJAAgEgFg");
	this.shape_8.setTransform(-18.5,-64.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgLAhQgGgDgFgFQgFgFgDgFQgCgHAAgIQAAgHACgGQADgGAFgGQAFgEAGgDQAGgCAHAAQAHAAAFACQAHACADAFQAFAEACAHQACAGAAAIIAAABIAAACIg0AAQAAAFADADQABAEADADQADADAEACQAEABADAAQAHAAAEgDQAFgDAEgEIAJAHQgGAHgHAEIgHACIgJABQgGAAgHgCgAAUgFIgBgHQgCgEgCgCQgCgDgDgCQgEgBgEAAQgEAAgDABQgFACgCADQgDACgBAEQgDADAAAEIAnAAIAAAAg");
	this.shape_9.setTransform(-24.7,-63.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgMAwQgKgEgHgGQgHgIgEgJQgEgKAAgLQAAgLAEgKQAEgJAHgHIAIgGIAJgFQAJgDAKAAIAMAAIAKADQAKAEAFAGIgJAKQgFgFgGgDIgIgCIgIgBQgIAAgHADQgHADgFAGQgFAFgDAHQgCAIAAAHQAAAIACAHQADAIAFAFQAFAGAHADQAHACAIAAIANgBIALgDIAAgcIgXAAIAAgLIAkAAIAAAwQgHAEgKACIgUACQgKAAgKgEg");
	this.shape_10.setTransform(-34.4,-65);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.seventeenordernow, new cjs.Rectangle(-41.7,-75.8,83.4,21.2), null);


(lib.seventeenbottomright_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.seventeenbottomright();
	this.instance.parent = this;
	this.instance.setTransform(-73.5,-65);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.seventeenbottomright_1, new cjs.Rectangle(-73.5,-65,147,130), null);


(lib.partystarted = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgsA1IgEgBQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAIAAhgQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAIAEgBIAoAAIAKABIALACQALAEAHAHQAIAHAFAKIADAKIABALQAAAMgEAKIgGAJIgHAIIgIAGIgKAFQgLADgKAAgAgdggQAAABAAAAQgBABAAAAQAAABAAAAQAAABAAAAIAAA6QAAABAAAAQAAABAAAAQABAAAAABQAAAAABAAIAEACIATAAQAHAAAGgDQAHgCAFgFQAGgEADgHQACgGAAgIQAAgHgCgGQgDgHgGgEQgFgFgHgCQgGgDgHAAIgTAAQgBAAAAAAQgBAAgBABQAAAAgBAAQAAABgBAAg");
	this.shape.setTransform(57.8,3.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AgkA1IgDgBQAAAAgBAAQAAgBAAAAQAAgBgBAAQAAAAAAgBIAAhiQAAAAAAAAQAAgBABAAQAAAAAAgBQAAAAABAAIADgBIBKAAIADACIABADIAAADIAAAEIgBAEIgDACIg3AAQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABgBAAIgBADIAAAPQAAAAAAABQAAAAAAABQAAAAABAAQAAABAAAAIAEABIAjAAQAAAAABAAQAAAAAAABQABAAAAAAQAAAAAAABIABAEIABAEIAAACQAAAFgEABIgjAAIgDACQgBAAAAABQgBAAAAABQAAAAAAAAQAAABAAAAIAAARQAAAAAAABQAAAAAAABQAAAAABABQAAAAAAAAQABABAAAAQAAAAABAAQAAABABAAQAAAAABAAIA2AAQADACAAAEIAAADIAAAEIgBAEQAAAAAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAg");
	this.shape_1.setTransform(46.6,3.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AgBA2IgFgBQgBgBAAAAQgBAAAAgBQAAAAgBgBQAAgBAAAAIAAhPQAAgBAAAAQAAAAAAgBQAAAAgBgBQAAAAAAgBIgFgBIgJAAIgIAAIgEAAQgDABgBgDIgBgFIAAgDIAAgEIACgDIADgBIBJAAQABAAABAAQAAAAABABQAAAAABAAQAAABAAAAIABAFIAAADIAAAEIgCADIgDABIgVAAIgFABQAAABAAAAQgBABAAAAQAAABAAABQAAAAAAABIAABOIgBADIgEABIgDABg");
	this.shape_2.setTransform(36.5,3.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AAbA2IgDgBIgCgBIgBgBIgTgcIgCgEIgFgBIgNAAIgEACQgBAAAAABQAAAAAAAAQgBABAAAAQAAABAAAAIAAAbQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAAAAAIgEACIgEAAIgEAAIgFgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAgBIAAhhQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAIADgBIAtAAQAIAAAHACQAHADAFAEQAFAFADAHQADAGAAAJQAAAJgDAFQgEAFgEAEIgHAFQgEACAAADIABACIAEAGIAGAJIAFAIIADAGIgBADIgEACIgEACIgDAAgAgWgiQAAAAgBABQAAAAAAABQgBAAAAABQAAABAAABIAAAYQAAAAAAABQAAABABAAQAAABAAAAQABABAAAAIAFABIAVAAQAFAAADgBIAHgDQADgCABgDQACgEAAgEQAAgJgGgFIgHgDIgIgBIgVAAIgFABg");
	this.shape_3.setTransform(27.1,3.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AAqA2IgDAAIgGAAQgDgCgBgCIgGgOIgCgDIgCgBIgkAAIgBAAIgCABIgCABIgBACIgGAOIgBACIgDABIgDABIgEAAIgCAAIgDAAIgEgCIgBgCIAshkQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAIADgBIAEABQABAAABAAQAAAAABAAQAAABABAAQAAAAAAABIAqBjIAAABQAAABAAAAQAAABAAAAQAAAAAAAAQgBABAAAAIgDABgAgCgOIgBACIgCAGIgCAFIgDAFIgCAFIgBADIABACIADABIAUAAIACgBIABgCIgCgFIgDgIIgEgJIgDgFIgCgBIAAAAg");
	this.shape_4.setTransform(16,3.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AgBA2IgFgBQgBgBAAAAQgBAAAAgBQAAAAgBgBQAAgBAAAAIAAhPQAAgBAAAAQAAAAAAgBQAAAAgBgBQAAAAAAgBIgFgBIgJAAIgIAAIgEAAQgDABgBgDIgBgFIAAgDIAAgEIACgDIADgBIBJAAQABAAABAAQAAAAABABQAAAAABAAQAAABAAAAIABAFIAAADIAAAEIgCADIgDABIgVAAIgFABQAAABAAAAQgBABAAAAQAAABAAABQAAAAAAABIAABOIgBADIgEABIgDABg");
	this.shape_5.setTransform(6.4,3.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AgXAzQgMgEgIgIIgBgCIgBgCIABgDIAEgEIAEgDIADgBIAFACIAHAFIAJAEQAFACAHAAIAIgBQAEAAAEgCQAEgCACgDQADgDAAgFQAAgEgDgDQgDgCgFgCIgLgCIgLgCIgNgCIgLgEQgFgEgDgFQgDgFAAgIQAAgJAEgGQAFgGAGgEQAGgEAIgCQAIgCAGAAIALABIAKADIAKAEQAFACAEAEIABACIAAACIgBAEIgEADIgEACIgEABIgDAAQgFgFgHgDQgGgDgHAAIgHABIgHACQgEACgCADQgCACAAAFQAAAGAFACQAFADAIABIAPACQAJABAIADQAHADAGAFQAFAGAAALQAAAJgFAHQgEAHgHAEQgHAFgIACQgIACgHAAQgMAAgLgFg");
	this.shape_6.setTransform(-3.2,3.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AgEA4IgCgBIgCgBIgBgCIAAgnIgBgFIgDgGIgeguIAAgBIABgEIADgDIAEgBIAEgBIADABIACABIAWAkIACABIACABIACgBIACgBIAWgkIADgCIADgBIAEABIAEABIADADIABADIAAACIAAABIgfAuIgDAHIAAACIgBACIAAAnQgBADgDAAIgGABg");
	this.shape_7.setTransform(-17.8,3.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AgBA2IgFgBQgBgBAAAAQgBAAAAgBQAAAAgBgBQAAgBAAAAIAAhPQAAgBAAAAQAAAAAAgBQAAAAgBgBQAAAAAAgBIgFgBIgJAAIgIAAIgEAAQgDABgBgDIgBgFIAAgDIAAgEIACgDIADgBIBJAAQABAAABAAQAAAAABABQAAAAABAAQAAABAAAAIABAFIAAADIAAAEIgCADIgDABIgVAAIgFABQAAABAAAAQgBABAAAAQAAABAAABQAAAAAAABIAABOIgBADIgEABIgDABg");
	this.shape_8.setTransform(-27.1,3.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AAbA2IgDgBIgCgBIgBgBIgTgcIgCgEIgFgBIgNAAIgEACQgBAAAAABQAAAAAAAAQgBABAAAAQAAABAAAAIAAAbQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAAAAAIgEACIgEAAIgEAAIgFgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAgBIAAhhQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAIADgBIAtAAQAIAAAHACQAHADAFAEQAFAFADAHQADAGAAAJQAAAJgDAFQgEAFgEAEIgHAFQgEACAAADIABACIAEAGIAGAJIAFAIIADAGIgBADIgEACIgEACIgDAAgAgWgiQAAAAgBABQAAAAAAABQAAAAgBABQAAABAAABIAAAYQAAAAAAABQABABAAAAQAAABAAAAQABABAAAAIAFABIAVAAQAFAAADgBIAHgDQADgCABgDQACgEAAgEQAAgJgGgFIgHgDIgIgBIgVAAIgFABg");
	this.shape_9.setTransform(-36.5,3.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AAqA2IgDAAIgFAAQgDgCgCgCIgFgOIgDgDIgDgBIgjAAIgBAAIgCABIgBABIgCACIgFAOIgCACIgDABIgDABIgDAAIgDAAIgDAAIgDgCIgCgCIAshkQAAgBABAAQAAAAAAgBQABAAAAAAQAAAAABAAIADgBIAFABQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIArBjIAAABQAAABgBAAQAAABAAAAQAAAAAAAAQgBABAAAAIgDABgAgBgOIgBACIgDAGIgDAFIgCAFIgCAFIAAADIAAACIADABIAUAAIACgBIABgCIgCgFIgDgIIgEgJIgDgFIgCgBIAAAAg");
	this.shape_10.setTransform(-47.6,3.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AgiA2IgDAAQgFAAgBgDIAAhlQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIADgBIAuAAQAHAAAHACQAHACAFAFQAFAEADAGQADAGAAAIIAAAGIgCAEQgDAKgIAFQgHAEgIACQgJACgIgBIgSAAIgCABIgCABIgBAEIAAAhIgCACIgEABgAgWghIgCAEIAAATIABADQABAAAAAAQAAABABAAQAAAAABAAQAAAAABAAIAaAAIAGgBIAGgDQACgBACgDQABgDAAgEQAAgDgBgCIgEgFIgFgCIgGgBIgaAAQgBAAAAAAQgBAAAAAAQgBAAAAABQgBAAAAAAg");
	this.shape_11.setTransform(-57.6,3.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AgkA1IgDgBQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAhiQAAAAAAAAQAAgBABAAQAAAAAAgBQAAAAABAAIADgBIBKAAIADACIABADIAAADIAAAEIgBAEIgDACIg3AAQAAAAgBAAQAAABAAAAQgBAAAAAAQAAABgBAAIgBADIAAAPQAAAAAAABQAAAAAAABQAAAAABAAQAAABAAAAIAEABIAjAAQAAAAABAAQAAAAAAABQABAAAAAAQAAAAAAABIABAEIABAEIAAACQAAAFgEABIgjAAIgDACIgCADIAAARQAAAAAAABQAAAAAAABQAAAAABABQAAAAAAAAQABABAAAAQAAAAABAAQAAABABAAQAAAAABAAIA2AAQADACAAAEIAAADIAAAEIgBAEQAAAAAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAg");
	this.shape_12.setTransform(28.9,-17.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AAcA2IgEgCIAAgmQAAgBAAgBQAAAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBAAAAAAIgkAAQAAAAgBAAQgBAAAAABQgBAAAAAAQgBABAAAAQgBABAAAAQgBABAAAAQAAABAAAAQAAABAAABIAAAkQAAAAAAABQgBAAAAABQAAAAAAAAQgBABAAAAIgEABIgEAAIgEAAIgEgCIgCgCIAAhmIADgCIADgBIAEAAIADAAQAFAAACAEIAAAiQAAABAAAAQAAABAAAAQAAABABAAQAAABAAAAQABAAAAABQAAAAABAAQAAABABAAQAAAAABAAIAkAAQABAAAAAAQABAAABAAQAAgBABAAQAAAAABAAQAAgBAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBIAAgiQADgDADgBIAGAAIAFABQAAAAABAAQAAABABAAQAAAAAAABQABAAAAABIAABlQgBAEgEgBIgGABg");
	this.shape_13.setTransform(17.5,-17.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AgBA2IgFgBQgBgBAAAAQgBgBAAAAQAAgBgBAAQAAgBAAgBIAAhOQAAAAAAgBQAAAAAAgBQAAAAgBgBQAAAAAAAAIgFgBIgJAAIgIAAIgEAAQgDgBgBgCIgBgFIAAgDIAAgEIACgDIADgBIBJAAQABAAABAAQAAAAABABQAAAAABAAQAAABAAAAIABAFIAAAEIAAADIgCAEIgDABIgVAAIgFABQAAAAAAAAQgBABAAAAQAAABAAABQAAAAAAABIAABNIgBAEIgEACIgDAAg");
	this.shape_14.setTransform(7.2,-17.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AgBA2IgFgBQgBgBAAAAQgBgBAAAAQAAgBgBAAQAAgBAAgBIAAhOQAAAAAAgBQAAAAAAgBQAAAAgBgBQAAAAAAAAIgFgBIgJAAIgIAAIgEAAQgDgBgBgCIgBgFIAAgDIAAgEIACgDIADgBIBJAAQABAAABAAQAAAAABABQAAAAABAAQAAABAAAAIABAFIAAAEIAAADIgCAEIgDABIgVAAIgFABQAAAAAAAAQgBABAAAAQAAABAAABQAAAAAAABIAABNIgBAEIgEACIgDAAg");
	this.shape_15.setTransform(-6.2,-17.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AgkA1IgDgBQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAhiQAAAAAAAAQAAgBABAAQAAAAAAgBQAAAAABAAIADgBIBKAAIADACIABADIAAADIAAAEIgBAEIgDACIg3AAQAAAAgBAAQAAABAAAAQgBAAAAAAQAAABgBAAIgBADIAAAPQAAAAAAABQAAAAAAABQAAAAABAAQAAABAAAAIAEABIAjAAQAAAAABAAQAAAAAAABQABAAAAAAQAAAAAAABIABAEIABAEIAAACQAAAFgEABIgjAAIgDACIgCADIAAARQAAAAAAABQAAAAAAABQAAAAABABQAAAAAAAAQABABAAAAQAAAAABAAQAAABABAAQAAAAABAAIA2AAQADACAAAEIAAADIAAAEIgBAEQAAAAAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAg");
	this.shape_16.setTransform(-15.2,-17.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("AgIA3IgLgEIgJgFIgJgGIgHgIQgDgFgDgFQgEgKAAgMIABgLQABgFACgFQAFgKAIgIQADgEAGgCIAJgGIALgDIAKgBIANACIALADQAMAFAIAKIAAACIgBADIgDAEIgFADIgDACQgCAAgDgDIgFgFIgJgFQgFgCgIAAQgGAAgHADQgGADgGAFQgEAFgDAHQgEAGAAAHQAAAHAEAHQADAHAEAFQAGAFAGADQAHADAGAAIAIgBIAHgBIAHgEIAEgGIABgBQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBgBIgDgBIgTAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAgBAAIgBgEIgBgEIAAgDIABgEIAEgCIAtAAIABABIACABQACAFAAAFIgBAEIgBAFQgCAIgGAGQgFAGgHAFQgGAEgJACQgHADgJAAIgKgBg");
	this.shape_17.setTransform(-27.4,-17.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.partystarted, new cjs.Rectangle(-65.6,-26.8,131.2,40.3), null);


(lib.partyreadyrecipes = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgJBFIgOgDIgEADIgEAAIgDAAIgDgCQgEgEgEgKQgEgLAAgKQAAgEADgDQACgDADAAQAGAAAHALIAFAIQAEAFAHADQAGADAHAAQAJAAAFgEQAFgEAAgIQAAgLgVgLIgIgDQgUgLgIgHQgHgJAAgMQAAgSAMgLQAMgKATAAIAJAAIAJACIAGgDIAEAAQAHAAAGAKQAGAKAAAMQAAAEgCADQgCADgEAAQgDAAgDgDQgDgCgEgHQgFgIgFgDQgFgDgHAAQgHAAgFAEQgFAEAAAHQAAAGAFAFQAFAFAQAIIABABQAlARAAAVQAAATgOAMQgOAMgWAAg");
	this.shape.setTransform(41.7,18.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AgqAyQgTgUAAgcQAAgeATgUQAUgUAdAAQAZAAAPAPQAPAOAAAZQAAAIgCADQgDACgJAAIgyAAQgFAAgCgCQgCgCAAgEQAAgDACgCQACgCAFAAIAaAAIAHgBQABAAAAAAQAAgBAAAAQABgBAAAAQAAgBAAgBQAAgNgJgIQgIgJgMAAQgQAAgHAOQgIANAAAUQAAAUALAPQAKAPAQAAQAKAAAHgCQAGgDAHgEIAFgEQAGgFAEAAQADAAACACQAAAAABABQAAAAAAABQABAAAAABQAAABAAAAQAAADgEAFIgJAJQgLAKgLAEQgLAEgMAAQgbAAgTgTg");
	this.shape_1.setTransform(29.1,18.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("Ag/BaQgIgCAAgGQAAgEAHgCIAGgEQADgCABgLQABgKAAghIAAgVQAAgkgBgKQgBgLgEgBIgFgDQgJgCABgFQAAgDABgCIAJgEIASgGQAJgDAEAAQAEAAABACQACACAAAFIAAAGIAAADIABABIAGgEIAEgEQAJgGAGgDQAIgCAIAAQAYAAAQASQAPASAAAcQAAAfgRAUQgSAVgbAAQgLAAgEgDQgEgEAAgFQAAgDACgCQACgCAEAAIADABIAFAAQAOAAAJgMQAJgMgBgUQAAgWgJgOQgJgOgPAAQgNAAgJAIQgHAHAAAUIAABTIAAAOQABAFACACIAHADIAGACIACACIABAEQAAAFgHACQgIACgTAAQgTAAgGgCg");
	this.shape_2.setTransform(13.9,21.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AgWBeQgHgCAAgGQAAgEAGgCIAEgCQADgCACgEQABgFAAgKIAAgJIAAgKIAAgOQAAgVgBgFQgBgGgDgCIgGgCQgIgDAAgEQAAgDACgCQADgDAGgCIAUgGIANgDQADAAACADQABACAAAGIAAAIIAAAGIgBAhIAAABIAAAgIABASQABAFADACIAFACQAGACAAAFQAAAFgGACQgGADgSAAQgTAAgGgDgAgPhCQgGgEAAgHQAAgIAGgFQAHgGAIAAQAIAAAGAFQAFAFAAAHQAAAIgGAFQgGAFgIAAQgJAAgFgFg");
	this.shape_3.setTransform(2.6,15.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AgpAyQgTgUAAgcQAAgeAUgUQAUgUAcAAQAXAAAPALQAPAMAAAPQAAAGgEAEQgFAEgGAAQgHAAgEgDQgEgDgFgLQgEgKgFgDQgFgEgIAAQgPAAgIALQgJALAAAVQABAWAMAPQAMAPASAAQAGAAAGgCQAGgBAGgEIAEgEQAIgFADAAQABAAABAAQABAAAAAAQABAAAAABQABAAAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAABAAABQAAADgCAFQgDAEgFAEQgKAJgLAFQgMAEgMAAQgbAAgTgTg");
	this.shape_4.setTransform(-7.7,18.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AgqAyQgTgUAAgcQAAgeATgUQAUgUAdAAQAZAAAPAPQAPAOAAAZQAAAIgCADQgDACgJAAIgyAAQgFAAgCgCQgCgCAAgEQAAgDACgCQACgCAFAAIAaAAIAHgBQABAAAAAAQAAgBAAAAQABgBAAAAQAAgBAAgBQAAgNgJgIQgIgJgMAAQgQAAgHAOQgIANAAAUQAAAUALAPQAKAPAQAAQAKAAAHgCQAGgDAHgEIAFgEQAGgFAEAAQADAAACACQAAAAABABQAAAAAAABQABAAAAABQAAABAAAAQAAADgEAFIgJAJQgLAKgLAEQgLAEgMAAQgbAAgTgTg");
	this.shape_5.setTransform(-21.6,18.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AAdBCQgNgqgJgIQgJgJgNAAQgLAAAAgIQAAgIAJAAQAVAAALgJQAKgIAAgTQAAgQgKgKQgLgIgUgBQgKABgEABQgEABgBAEIgCALIAAAbIAAA6IABAnQAAAKADABIAGAEQAIADAAAFQAAAGgHACQgIACgVABQgUgBgIgCQgHgCAAgGQAAgFAIgDIAGgEQADgBABgRIABg4IgBgyQgBgTgCgCQgBgCgHgEQgHgCAAgFQAAgFAEgCQAEgCAIAAIAdAAIAbgBIAUgBQAdAAAPANQAQAMAAAYQAAAQgKANQgLANgSAFIAAABQAOADAIAJQAIAJAHAVIADANQAFAUAIABIAEAAIAFgBQAAAAABAAQABAAAAAAQABABAAAAQABAAAAABQACACAAADQAAAGgHAEQgIAEgMAAQgbAAgIgfg");
	this.shape_6.setTransform(-37.7,15.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("Ag8BXQgGgFgBgIQABgHAEgFQAFgFAGAAIAGABIAEADIAEAFQADAGADAAQAGAAAIgKQAGgKAAgKQABgMgKgVIgCgDIgUgtIgMgaQgDgFgIgDIAAAAQgFgCgBgCQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAgGAGgCQAHgDAUAAQATAAAGACQAHACAAAGIAAAEIgDACIgFADQgFACAAACIADAKIALAaIAJAZQAEAGACAAQABAAADgGIAIgVIAKgaQADgJABgEQAAgDgIgFQgHgEAAgDQgBgFAHgCQAGgCAPAAQAPAAAGACQAFACABAGQgBAFgHABIgGACQgHAEgIAXIgEAKIgRAqQgWA3gNAQQgOARgTAAQgKAAgGgGg");
	this.shape_7.setTransform(67.3,-10);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("Ag5BQQgQgSAAgdQAAggASgTQASgUAcAAIAJABQAEABACADQACADAAADQAAAHgIAAIgDAAIgEAAQgPAAgIAMQgJALAAAVQAAAWAKAOQAJAOAPAAQANAAAIgIQAHgIAAgOIAAglIAAg8QAAgJgBgDQgCgEgFgCIgEgBQgIgCAAgFQAAgDADgDQAEgDAKgDIAOgEIANgCQAEAAACADQACACAAAGIAAAHIgCBQIABA4QABAMACACIAKADQAHACAAAEQAAAGgUAHIgNADIgKABQgEAAgBgCQgCgCAAgEIAAgHIAAgCIgBgBIgEADIgGAEQgIAGgGADQgIADgIAAQgZAAgPgSg");
	this.shape_8.setTransform(53.2,-15.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AAYA+IgHgHIgGADQgQALgQAAQgTAAgMgLQgMgMAAgSQAAgVAPgLQAPgLAcgBQAGAAADACQAEACAAAFQAAAIgJgBQgNAAgIAHQgIAGAAALQAAALAHAGQAHAGAMAAQAMAAAFgFQAGgGAAgOIAAgxQAAgMgFgGQgFgGgJgBQgGAAgGADQgFADgGAGIgCAEQgIAKgJAAQgGAAgDgDQgDgEAAgFQAAgNAPgJQAQgIAYAAQAOAAAKAEQALAEAGAHQAEAFABAIQACAIAAATIAAAqQAAAHABAEQABADADACIAEAAQAIADAAAFQAAAFgIAGQgJAFgMAAQgGAAgGgHg");
	this.shape_9.setTransform(38,-12.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AgqAyQgTgUAAgcQAAgeATgUQAUgUAdAAQAZAAAPAPQAPAOAAAZQAAAIgCADQgDACgJAAIgyAAQgFAAgCgCQgCgCAAgEQAAgDACgCQACgCAFAAIAaAAIAHgBQABAAAAAAQAAgBAAAAQABgBAAAAQAAgBAAgBQAAgNgJgIQgIgJgMAAQgQAAgHAOQgIANAAAUQAAAUALAPQAKAPAQAAQAKAAAHgCQAGgDAHgEIAFgEQAGgFAEAAQADAAACACQAAAAABABQAAAAAAABQABAAAAABQAAABAAAAQAAADgEAFIgJAJQgLAKgLAEQgLAEgMAAQgbAAgTgTg");
	this.shape_10.setTransform(23.8,-12.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AAdBCQgNgqgJgJQgJgIgNAAQgLAAAAgIQAAgIAJAAQAVAAALgIQAKgJAAgSQAAgSgKgIQgLgKgUABQgKgBgEACQgEABgBAEIgCAMIAAAbIAAA5IABAoQAAAJADACIAGACQAIADAAAGQAAAFgHADQgIACgVAAQgUAAgIgCQgHgDAAgFQAAgGAIgDIAGgCQADgCABgQIABg5IgBgyQgBgTgCgCQgBgDgHgDQgHgCAAgFQAAgFAEgDQAEgCAIAAIAdAAIAbAAIAUgBQAdAAAPAMQAQANAAAXQAAASgKANQgLAMgSAFIAAACQAOACAIAJQAIAIAHAWIADANQAFAVAIgBIAEAAIAFAAQAAAAABAAQABAAAAABQABAAAAAAQABABAAAAQACACAAADQAAAGgHAEQgIAEgMAAQgbAAgIgfg");
	this.shape_11.setTransform(7.6,-15.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AgZAOQgEAAgCgCQgCgBAAgEIABgGIADgHQACgEACgBQACgBAGAAIAGAAIALAAIAWgBIAEAAQAEAAACACQACABAAAEQAAAGgEAHQgEAGgHAAIgGAAIgHgBIgdACIgCAAg");
	this.shape_12.setTransform(-6.6,-12.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("Ag8BXQgGgFAAgIQAAgHAEgFQAFgFAHAAIAFABIAFADIADAFQADAGADAAQAHAAAGgKQAIgKgBgKQAAgMgJgVIgBgDIgVgtIgNgaQgCgFgIgDIAAAAQgEgCgCgCQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBgBAAAAQAAgGAHgCQAIgDATAAQATAAAHACQAGACAAAGIgBAEIgCACIgFADQgFACAAACIACAKIAMAaIAKAZQADAGABAAQACAAADgGIAJgVIAKgaQACgJAAgEQAAgDgHgFQgIgEABgDQAAgFAFgCQAGgCAQAAQAQAAAFACQAGACAAAGQAAAFgIABIgGACQgHAEgJAXIgDAKIgRAqQgVA3gOAQQgOARgTAAQgKAAgGgGg");
	this.shape_13.setTransform(-17.6,-10);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AgGBPQgHgCgFgEQgEgEgCgIQgCgHAAgUIAAhGIgMAAIgEgBIgBgDIAAgDQAAgFAOgLIAFgFIAFgEQAOgNAFAAIADACQABAAAAAAQAAAAAAABQABAAAAABQAAAAAAABIAAAZIAdAAQABAAABAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAABABQAAAAAAABQAAABAAAAIAAAEIgBAFQgBAAAAABQgBAAAAAAQgBAAAAAAQgBAAgBAAIgbAAIgCACIgBADIAABAQAAARADAFQADAEAIAAQAEAAAGgCIAJgCQADAAACACQABAAAAAAQABABAAAAQAAABAAABQAAAAAAABQAAAHgLAHQgLAHgPAAQgHgBgGgCg");
	this.shape_14.setTransform(-28.9,-13.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AgnBBQgHgCAAgGQAAgEAHgCIADgCQAEgCABgEQABgFAAgKIAAgJIAAgKIAAgIQAAgYgBgHQgBgHgDgCIgGgCQgIgDAAgEQAAgDADgCQACgDAGgCIASgGIALgCQAHAAACASIAAACIABABQAGgLAIgFQAHgGAIAAQAJAAAFAGQAGAFAAAJQAAAKgEAFQgFAFgHAAIgHgBIgFgEIgDgFQgBgBAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAQgJAAgEANQgDANAAAnQAAALABAGQABAGAEACIAFABQAIADAAAFQAAAFgHACQgHADgSAAQgUAAgGgDg");
	this.shape_15.setTransform(-38.4,-12.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AAYA+IgHgHIgGADQgQALgQAAQgTAAgMgLQgMgMAAgSQAAgVAPgLQAPgLAcgBQAGAAADACQAEACAAAFQAAAIgJgBQgNAAgIAHQgIAGAAALQAAALAHAGQAHAGAMAAQAMAAAFgFQAGgGAAgOIAAgxQAAgMgFgGQgFgGgJgBQgGAAgGADQgFADgGAGIgCAEQgIAKgJAAQgGAAgDgDQgDgEAAgFQAAgNAPgJQAQgIAYAAQAOAAAKAEQALAEAGAHQAEAFABAIQACAIAAATIAAAqQAAAHABAEQABADADACIAEAAQAIADAAAFQAAAFgIAGQgJAFgMAAQgGAAgGgHg");
	this.shape_16.setTransform(-50.7,-12.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("AhEBeQgHgDAAgFQAAgGAIgDIAGgDQACgCACgQIABg4IgBgyQgBgTgCgDQgCgCgGgDQgIgCABgFQgBgFAFgDQAEgCAIAAIAOAAIAPAAIAbAAIAUgBQAeAAAOANQAPAMABAZQAAAcgTAPQgSANgjAAQgNAAAAgJQAAgIALAAQAQAAALgJQAKgJAAgTQAAgSgKgJQgLgJgVAAQgKAAgDACQgEABgBAEIgCAMIAAAcIAAA5IABAmQABAKABABIAHADQAHADABAGQgBAFgGADQgIACgVAAQgUAAgIgCg");
	this.shape_17.setTransform(-65.4,-15.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.partyreadyrecipes, new cjs.Rectangle(-75.8,-33.4,151.7,66.9), null);


(lib.mainbutton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("EgQFAzRMAAAhmhMAgLAAAMAAABmhg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.holidayhostingtips = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgJBFIgOgDIgEADIgEAAIgDAAIgDgCQgEgEgEgKQgEgLAAgKQAAgEADgDQACgDADAAQAGAAAHALIAFAIQAEAFAHADQAGADAHAAQAJAAAFgEQAFgEAAgIQAAgLgVgLIgIgDQgUgLgIgHQgHgJAAgMQAAgSAMgLQAMgKATAAIAJAAIAJACIAGgDIAEAAQAHAAAGAKQAGAKAAAMQAAAEgCADQgCADgEAAQgDAAgDgDQgDgCgEgHQgFgIgFgDQgFgDgHAAQgHAAgFAEQgFAEAAAHQAAAGAFAFQAFAFAQAIIABABQAlARAAAVQAAATgOAMQgOAMgWAAg");
	this.shape.setTransform(20.1,34.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("Ag/BaQgIgCAAgGQAAgEAHgCIAGgEQADgCABgLQABgKAAghIAAgVQAAgkgBgKQgBgLgEgBIgFgDQgJgCABgFQAAgDABgCIAJgEIASgGQAJgDAEAAQAEAAABACQACACAAAFIAAAGIAAADIABABIAGgEIAEgEQAJgGAGgDQAIgCAIAAQAYAAAQASQAPASAAAcQAAAfgRAUQgSAVgbAAQgLAAgEgDQgEgEAAgFQAAgDACgCQACgCAEAAIADABIAFAAQAOAAAJgMQAJgMgBgUQAAgWgJgOQgJgOgPAAQgNAAgJAIQgHAHAAAUIAABTIAAAOQABAFACACIAHADIAGACIACACIABAEQAAAFgHACQgIACgTAAQgTAAgGgCg");
	this.shape_1.setTransform(6.3,36.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AgWBeQgHgCAAgGQAAgEAGgCIAEgCQADgCACgEQABgFAAgKIAAgJIAAgKIAAgOQAAgVgBgFQgBgGgDgCIgGgCQgIgDAAgEQAAgDACgCQADgDAGgCIAUgGIANgDQADAAACADQABACAAAGIAAAIIAAAGIgBAhIAAABIAAAgIABASQABAFADACIAFACQAGACAAAFQAAAFgGACQgGADgSAAQgTAAgGgDgAgPhCQgGgEAAgHQAAgIAGgFQAHgGAIAAQAIAAAGAFQAFAFAAAHQAAAIgGAFQgGAFgIAAQgJAAgFgFg");
	this.shape_2.setTransform(-5,31.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AgbBeQgIgCAAgGQAAgFAIgDQAHgDABgCQACgCAAgWIABg9IAAgjIgBgWQAAgDgDgBIgIgBIgGAAQgIAAgFACQgFACgEAFIgFAJIgDAJIgEAEIgFABQgEABgCgEQgCgEAAgHQABgSAEgKQAEgMAGAAIABABQALACAQAAIBNAAQAQAAALgCIABgBQAHAAAEAMQADAKAAASQAAAHgBAEQgCAEgEgBIgFgBIgDgEIgFgJIgDgJQgEgFgFgCQgGgCgJAAIgFAAIgHABQgDABgBADIgBAWIAAAjIAAA9QABAWACACQACACAGADQAIADgBAFQAAAGgHACQgIACgUABQgUgBgHgCg");
	this.shape_3.setTransform(-17.3,31.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AgxBWQgQgKAAgPQAAgGAEgFQADgEAHAAQAGAAADADQADAEACAGQADAKAIAFQAIAGARgBQAQABAMgIQALgHAAgJQAAgHgDgDQgFgDgJgBIgOABIgUACQgYAAgNgIQgMgIAAgLQAAgHAEgGQAFgFAKgGQgIgGgEgJQgEgJAAgKQAAgVAQgPQAQgOAaAAIAMABIAVAEQAEAAAHgCQAGgDAHgFIAFADIABAFQAAAGgEAFQgEAFgIAEIAEAKIACALQAAAXgQANQgQANgaAAIgNgBIgNgCIgEAFIgBAEQAAAGAFADQAHAEANAAIAUgCIAUgCQATAAAJAIQAKAHAAAPQAAAUgVAPQgVAOgfgBQgYABgSgLgAgVhBQgHAIAAANQAAAOAGAJQAIAHAKABQAKgBAIgHQAHgJAAgNQAAgOgHgIQgHgJgLAAQgKAAgHAJg");
	this.shape_4.setTransform(39.9,5.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AhABBQgHgCAAgGQAAgEAGgCIAEgCQAEgCABgEQACgFAAgKIgBgJIAAgKIAAgNQAAgVgBgGQgBgGgDgCIgGgCQgIgDAAgEQAAgDADgCQACgDAGgCIATgGIANgCQAFAAABACQABACAAAEIAAAJIABABIAAAAIABAAIABAAIADgDIADgCQAOgOAQAAQAKAAAIAEQAJAEAGAHQAGAIACAKQADAKAAAVIAAARIAAAJIAAAHQAAAJABAEQACAEADACIADACQAHACAAAEQAAAGgGACQgHACgUAAQgSAAgGgCQgHgCAAgFQABgFAGgCIAFgCQADgCABgGQABgGABgOQgBgpgFgLQgGgKgOAAQgFAAgHAEQgGAEgDAHQgEAGgBAKIgBAkQAAANABAEQABAEADACIAFACQAGACABAFQgBAFgGACQgGADgSAAQgUAAgGgDg");
	this.shape_5.setTransform(24.5,3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AgWBeQgHgCAAgGQAAgEAGgCIAEgCQADgCACgEQABgFAAgKIAAgJIAAgKIAAgOQAAgVgBgFQgBgGgDgCIgGgCQgIgDAAgEQAAgDACgCQADgDAGgCIAUgGIANgDQADAAACADQABACAAAGIAAAIIAAAGIgBAhIAAABIAAAgIABASQABAFADACIAFACQAGACAAAFQAAAFgGACQgGADgSAAQgTAAgGgDgAgPhCQgGgEAAgHQAAgIAGgFQAHgGAIAAQAIAAAGAFQAFAFAAAHQAAAIgGAFQgGAFgIAAQgJAAgFgFg");
	this.shape_6.setTransform(12.8,0.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AgGBPQgHgCgFgEQgEgEgCgIQgCgHAAgUIAAhGIgMAAIgEgBIgBgDIAAgDQAAgFAOgLIAFgFIAFgEQAOgNAFAAIADACQABAAAAAAQAAAAAAABQABAAAAABQAAAAAAABIAAAZIAdAAQABAAABAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAABABQAAAAAAABQAAABAAAAIAAAEIgBAFQgBAAAAABQgBAAAAAAQgBAAAAAAQgBAAgBAAIgbAAIgCACIgBADIAABAQAAARADAFQADAEAIAAQAEAAAGgCIAJgCQADAAACACQABAAAAAAQABABAAAAQAAABAAABQAAAAAAABQAAAHgLAHQgLAHgPAAQgHgBgGgCg");
	this.shape_7.setTransform(4.6,1.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AgJBFIgOgDIgEADIgEAAIgDAAIgDgCQgEgEgEgKQgEgLAAgKQAAgEADgDQACgDADAAQAGAAAHALIAFAIQAEAFAHADQAGADAHAAQAJAAAFgEQAFgEAAgIQAAgLgVgLIgIgDQgUgLgIgHQgHgJAAgMQAAgSAMgLQAMgKATAAIAJAAIAJACIAGgDIAEAAQAHAAAGAKQAGAKAAAMQAAAEgCADQgCADgEAAQgDAAgDgDQgDgCgEgHQgFgIgFgDQgFgDgHAAQgHAAgFAEQgFAEAAAHQAAAGAFAFQAFAFAQAIIABABQAlARAAAVQAAATgOAMQgOAMgWAAg");
	this.shape_8.setTransform(-6,3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AgvAyQgTgUAAgdQAAgdAUgUQATgUAdAAQAdAAASATQASASAAAdQAAAegTAUQgUAVgcAAQgcAAgTgTgAgYgnQgIALAAASQAAAZALASQALARAPAAQANAAAIgLQAIgKAAgSQAAgZgLgSQgMgRgOAAQgNAAgIAKg");
	this.shape_9.setTransform(-19,3.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AAdBdQgHgDAAgFQAAgGAJgDIAFgCQADgCABgIIAAggIAAgSIgBgFQgBgDgHgBQgGgBgZAAIgbABQgIABgCACIgBAEIgBAJIAAALIABAgQABAIACACIAGACQAIADAAAGQAAAFgHADQgIACgVAAQgUAAgIgCQgHgDAAgFQAAgGAIgDIAGgCQADgCABgRIABg4IgBgxQgBgUgCgCQgBgDgHgCQgHgDAAgGQAAgFAGgCQAGgCAYAAQAXAAAGACQAGACAAAFQAAAGgIADIgGADQgCACgBAIIgBAnQAAAFAFACQAFACATAAIAKAAIAcAAQAIgBADgDIABgCIAAgFIAAgGIAAghQgBgGgDgCIgFgDQgJgDAAgGQAAgFAGgCQAHgCAXAAQAYAAAFACQAGACAAAFQAAAGgIADIgGADQgDACgBASQgBARAAAkIABAyQABAVACACQABACAHADQAHACAAAGQAAAFgHADQgIACgUAAQgVAAgIgCg");
	this.shape_10.setTransform(-36.4,0.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("Ag8BXQgGgFAAgIQgBgHAFgFQAFgFAHAAIAFABIAFADIADAFQADAGADAAQAHAAAGgKQAIgKAAgKQgBgMgJgVIgBgDIgWgtIgMgaQgCgFgIgDIAAAAQgEgCgCgCQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBgBAAAAQAAgGAIgCQAGgDAUAAQATAAAHACQAGACAAAGIgBAEIgCACIgFADQgFACAAACIACAKIALAaIALAZQADAGABAAQACAAADgGIAJgVIAKgaQACgJAAgEQAAgDgHgFQgIgEAAgDQABgFAFgCQAHgCAOAAQARAAAFACQAGACgBAGQABAFgIABIgGACQgHAEgJAXIgDAKIgRAqQgVA3gOAQQgOARgTAAQgKAAgGgGg");
	this.shape_11.setTransform(39.9,-25.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AAYA+IgHgHIgGADQgQALgQAAQgTAAgMgLQgMgLAAgSQAAgWAPgLQAPgLAcAAQAGAAADACQAEABAAAGQAAAGgJABQgNAAgIAFQgIAHAAALQAAAKAHAHQAHAGAMABQAMAAAFgHQAGgFAAgOIAAgyQAAgLgFgGQgFgHgJABQgGAAgGACQgFADgGAGIgCADQgIAKgJAAQgGAAgDgDQgDgDAAgGQAAgMAPgIQAQgJAYAAQAOAAAKADQALAFAGAHQAEAFABAIQACAIAAATIAAAqQAAAIABADQABAEADAAIAEACQAIACAAAEQAAAHgIAFQgJAFgMAAQgGAAgGgHg");
	this.shape_12.setTransform(26.3,-28.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("Ag5BQQgQgSAAgdQAAggASgTQASgUAcAAIAJABQAEABACADQACADAAADQAAAHgIAAIgDAAIgEAAQgPAAgIAMQgJALAAAVQAAAWAKAOQAJAOAPAAQANAAAIgIQAHgIAAgOIAAglIAAg8QAAgJgBgDQgCgEgFgCIgEgBQgIgCAAgFQAAgDADgDQAEgDAKgDIAOgEIANgCQAEAAACADQACACAAAGIAAAHIgCBQIABA4QABAMACACIAKADQAHACAAAEQAAAGgUAHIgNADIgKABQgEAAgBgCQgCgCAAgEIAAgHIAAgCIgBgBIgEADIgGAEQgIAGgGADQgIADgIAAQgZAAgPgSg");
	this.shape_13.setTransform(11.7,-31.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AgWBeQgHgCAAgGQAAgEAGgCIAEgCQADgCACgEQABgFAAgKIAAgJIAAgKIAAgOQAAgVgBgFQgBgGgDgCIgGgCQgIgDAAgEQAAgDACgCQADgDAGgCIAUgGIANgDQADAAACADQABACAAAGIAAAIIAAAGIgBAhIAAABIAAAgIABASQABAFADACIAFACQAGACAAAFQAAAFgGACQgGADgSAAQgTAAgGgDgAgPhCQgGgEAAgHQAAgIAGgFQAHgGAIAAQAIAAAGAFQAFAFAAAHQAAAIgGAFQgGAFgIAAQgJAAgFgFg");
	this.shape_14.setTransform(-0.5,-31.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AgVBfQgHgCAAgGQAAgEAFgDIAHgDQACgCACgIIABgbIgBgUIAAgYIAAgLQAAghgBgJQgBgKgDgCIgIgCQgJgDAAgEQABgEACgCQADgCAJgDIASgFIAMgCQAFAAABACQACADAAAGIgBAKQgBAvAAAvIABAtQABAKACACIAHAEQAHADAAAFQgBAFgGACQgHACgRAAQgTAAgGgCg");
	this.shape_15.setTransform(-8,-31.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AgvAyQgTgUAAgdQAAgdAUgUQATgUAdAAQAdAAASATQASASAAAdQAAAegTAUQgUAVgcAAQgcAAgTgTgAgYgnQgIALAAASQAAAZALASQALARAPAAQANAAAIgLQAIgKAAgSQAAgZgLgSQgMgRgOAAQgNAAgIAKg");
	this.shape_16.setTransform(-19,-28.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("AAdBdQgHgCAAgGQAAgFAJgDIAFgEQADgBABgJIAAgeIAAgTIgBgFQgBgCgHgBQgGgCgZAAIgbABQgIABgCABIgBAFIgBAKIAAALIABAeQABAJACABIAGAEQAIADAAAFQAAAGgHACQgIACgVABQgUgBgIgCQgHgCAAgGQAAgFAIgDIAGgEQADgBABgSIABg3IgBgxQgBgUgCgDQgBgCgHgCQgHgDAAgFQAAgGAGgBQAGgCAYAAQAXAAAGACQAGABAAAGQAAAFgIADIgGADQgCACgBAIIgBAnQAAAFAFACQAFACATAAIAKAAIAcgBQAIgBADgCIABgCIAAgGIAAgFIAAggQgBgHgDgCIgFgDQgJgDAAgFQAAgGAGgBQAHgCAXAAQAYAAAFACQAGABAAAGQAAAFgIADIgGADQgDACgBASQgBARAAAkIABAzQABATACADQABACAHADQAHADAAAFQAAAGgHACQgIACgUABQgVgBgIgCg");
	this.shape_17.setTransform(-36.4,-31.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidayhostingtips, new cjs.Rectangle(-48.4,-49.1,96.9,98.4), null);


(lib.greyrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(1,1,1).p("EgL3guZIXvAAMAAABc0I3vAAg");
	this.shape.setTransform(0,0,1.046,1.008);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.greyrectangle, new cjs.Rectangle(-80.5,-300.5,161,601), null);


(lib.greenlogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgeAfQgNgNAAgSQAAgRANgNQANgNARAAQASAAANANQANANAAARQAAASgNANQgNANgSAAQgRAAgNgNgAgYgYQgKAKAAAOQAAAQAKAKQAKAKAOAAQAPAAAKgKQAKgKAAgQQAAgOgKgKQgKgKgPAAQgOAAgKAKgAAMAZIgOgVIgFAAIAAAVIgJAAIAAgzIATAAQARAAAAAPQAAANgNABIAPAWgAgHgDIAGAAQANAAAAgIQAAgHgMAAIgHAAg");
	this.shape.setTransform(35,15.9,0.268,0.268);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjnEaQgVgDgGgEQgKgFAAgNQAAgKAFgHQAHgHAIAAIARAAQAKAAAFgLQACgKABgXIAAl5QgBgXgCgKQgFgLgKAAIgRAAQgIAAgHgHQgFgHAAgKQAAgNAKgFQAGgEAVgDQBdgNBrAAQBOAAA2ASQA0ASAnAoQAlAlAUA5QAUA4AABEQAABNgZA9QgaA+guAlQglAegxAOQgwAOhFAAQhrAAhdgNgAgwjrQgcAFgJALQgKAMAAAhIAAFjQAAAhAUALQAOAHAnADQBMAEAthAQAqg/AAhwQAAhwgqg/Qgrg/hKAAIgeADg");
	this.shape_1.setTransform(16.7,8.1,0.268,0.268);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNBlQgFgDAAgHIAAiTQAAgKgMAAIgyAAQgKAAAAgPIABgNQACgIAHAAICfAAQAMAAAAASQAAASgLAAIgyAAQgMAAAAAKIABCTQAAAHgFADQgEACgKAAQgJAAgEgCg");
	this.shape_2.setTransform(21.8,23.7,0.268,0.268);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhMBmQgNAAAAgPIAAiuQAAgOANAAICbAAQAGAAADAFQACADAAAJQAAAKgCADQgDAGgHAAIh5AAQgIAAAAAJIAAAbQAAAKAKAAIBFAAQALAAAAASQAAAQgKAAIhFAAQgLAAAAALIAAAeQAAAKAKAAIB4AAQAKAAAAATQAAARgKAAg");
	this.shape_3.setTransform(14.1,23.7,0.268,0.268);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAxBgIhAhGQgLgJgTAAQgFAAgEAEQgDAFAAAGIAAA8QAAAMgVAAQgRAAAAgNIAAi0QAAgIAFgCQAEgCALAAQASAAAAAMIAAA3QAAANAJAAQALAAAFgDQAEgBAFgFIBJhDQANgLAMAMQAMALgKAKIhAA6QgJAIAJAJIBOBWQAIAIgGAFQgFAFgNAAQgTAAgHgIg");
	this.shape_4.setTransform(6.1,23.7,0.268,0.268);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAuBeIgfgyQgGgJgKAAIgtAAQgDAAgEADQgEAEABADIAAAyQAAAGgKACIgPAAQgMAAAAgMIAAi5QgBgIAKAAIBqAAQAgAAAUATQAVATAAAfQAAAYgPAPQgIAJgPAKQgHAGADAGIAjAyQAFAIgFADQgEAFgPAAQgQAAgHgJgAg4g4IAAAuQAAAFAEADQAEACAFAAIA+AAQAQAAALgIQALgIAAgRQAAgQgLgJQgLgJgQABIg+AAQgNAAAAAKg");
	this.shape_5.setTransform(-3,23.7,0.268,0.268);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("ABCBgIgOgbQgCgHgHAAIhTAAQgJAAgEALIgMAXQgDAHgSAAQgWAAAFgMIBZi4QAFgKAKAAQALAAAFAJIBXC6QADAGgJAEQgGACgIAAQgPAAgDgIgAgEgdIgYAyQgDAIAIAAIAwAAQABAAABAAQAAAAABgBQABAAAAAAQAAgBABAAQACgCgCgDIgZgzQgBgDgEAAQgCAAgCADg");
	this.shape_6.setTransform(-11.9,23.7,0.268,0.268);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ABZBkQgFgDAAgEIgOhsQgCgGgFAAQgDAAgDADIgxA+QgEAGgFAAQgHAAgEgHIgtg7QgCgDgEAAQgFAAgBAHIgOBoQgCALgTAAQgGAAgFgDQgGgDAAgFIAViwQACgJADgEQAEgEALAAQAKAAAFAJIA4BPQAFAHAEAAQAEAAAHgIIA7hQQAEgIALAAQAGAAADACQAEADACAIIAVC1QABALgXAAQgFAAgFgDg");
	this.shape_7.setTransform(-21,23.7,0.268,0.268);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AipF/QhPhTAAiLQAAhZAghEQAghCA6gnQAZgTAmgTQAmgTAngOQAKgDgDgJQgCgKgNADQg7ALgrgSQgWgJgdgRQghgUgJgEQgvgWg6AZQgVAJgMgLQgLgLAGgXQAXhWBDg3QBKg9BQAXQA0APAlA0QAmA2AfALQATAGgBAPQAAAOgRADQgaAFgjgRQgggPgdgbQgfgcgvgCQgsgCgbAVQgLAIADAHQAEAHAKgDQAggHAdAGQAoAIAbAgQAkAoAuAPQA4ASAugfIAZgWQANgNAMAEQAPAEgBAUQgBAUgTAZQgiAsg+AeQhFAjgeAdQgwAwgTA9QgPAzAABQQAAByAqBAQAqBABKAAQBKAAArhCQAqhBAAhwQAAhfgXg4QgZg6g2gVQgbgKAFgTQAFgUAhgEQA3gGA8AsQBoBOAACjQAACOhPBVQhQBUiHAAQiDAAhPhUg");
	this.shape_8.setTransform(3.9,-14.6,0.268,0.268);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("ABnDwQhFg1gYheIgBgCQgCgMgHAAQgGAAgCALIgBACQgYBfhGA1QhIA3hoAAQh+AAhMhQQhMhQAAiFQAAiHBMhRQBLhQCAAAQBpAABHA3QBHA2AXBgQACALAGAAQAHgBACgKIABgBQAXhgBGg1QBHg3BoAAQB/AABNBQQBMBPAACFQAACHhMBRQhNBRiBAAQhmAAhHg3gACniqQgpA/AABuQAABrApA/QAoA9BIAAQBGAAApg/QApg/AAhrQAAhsgqg+QgphAhHAAQhGAAgoA/gAmFiqQgoA/AABuQAABsAoA+QAoA9BIAAQBGAAApg/QApg/AAhrQAAhsgqg+QgphAhHAAQhGAAgoA/g");
	this.shape_9.setTransform(-5.6,8.1,0.268,0.268);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ai5EbQgWAAgJgFQgIgFAAgOQAAgKAGgHQAHgHAJAAIARAAQAKAAAEgLQADgJAAgYIAAl7QAAgXgDgKQgCgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgJQAAgOAJgGQAIgFAWAAIFvAAQAaAAAEAVIAMA7QAEAQgFAJQgFAJgMAAQgPAAgHgOQgEgFgFgNQgFgQgPgFQgNgEggAAIhtAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAFADAdAAIBFAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAJgOAAQgTAAgEgXIAAgFQgCgNgIgDQgHgEgbAAIhFAAQgeAAgEAEQgIAFAAAZIAACLQAAAbACAGQAGALAMAAIATAAQAKAAAGAHQAGAHAAAKQAAAOgJAFQgIAFgYAAg");
	this.shape_10.setTransform(-26.4,8.1,0.268,0.268);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhTEbIgTgEQgIAAgKAJQgKAIgJAAQgLAAgGgHQgGgGgEgQIgVhUQgCgIAAgJQAAgMAHgIQAIgHAMAAQAMAAAJALIAMARQAWAfAhASQAiASAkAAQApAAAagVQAZgUAAgiQAAghgbgfQgbgdg/gsIhNg2QgSgPgTgWQgggmAAgzQAAg9ArgmQArgmBGAAQAlAAAjAIIAWAFIALACQAJAAALgIIAJgFQAEgCAFAAQASAAAGAYIAUBcQABAEAAAIQAAAIgHAGQgHAGgKAAQgMAAgLgOQgNgVgHgIQgGgGgOgLQgjgbgtAAQgcAAgSAPQgRAQAAAaQAAAXAJALQAMASAbAWIApAdQAzAkAWARQAXASAUAUQAWAWAMAfQAMAeAAAhQAABJgyAtQgzAthUAAQgzAAglgNg");
	this.shape_11.setTransform(29.5,8.1,0.268,0.268);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ah+EYQgLgJgHgYIhJjYQgBgFgEAAQgFAAgBAFIhNDYQgKAagHAHQgNAJgQAAQgTAAgKgJQgLgJgJgYIimm+QgKgagHgHQgHgHgUgFQgOgCgFgFQgFgFAAgLQAAgVAdgBICvAAQAcAAAAAYQAAAKgHAFQgHAFgRABQgOACgGAFQgGAFAAAJQAAAJADAKIBzFHQACAGAFgBQAEAAACgGIA/i2QAIgYgHgYIglhuQgEgJgHgFQgGgEgPgEQgNgDgGgGQgFgEAAgKQAAgaAdAAICnAAQAdAAAAAYQAAASgcAEQgRACgFAFQgGAFAAAMQAAAKAIAZIBfEsQACAFAEAAQAFAAABgGIBdk6QAEgLAAgJQAAgSgdgEQgbgCAAgVQAAgNAHgGQAIgFARgBIElAAQAVABAIAFQAIAFAAAOQAAAKgGAIQgGAGgJAAIgQAAQgLAAgFALQgCAIAAAZIAABtQAAAeAFAGQAGAHAXAAIB0AAQAXAAAHgIQADgDAAgHIABgdIAAhpQAAgbgDgGQgFgLgKAAIgQAAQgKAAgHgGQgGgIAAgKQAAgOAIgFQAJgFAWgBICaAAQAWABAJAFQAJAFAAAOQAAAKgHAIQgGAGgJAAIgSAAQgEAAgEADQgFADgBAFQgDAJAAAYIAAF9QAAAXADAKQABAFAFACQAEADAEABIASAAQAJAAAGAGQAHAIAAAJQAAAOgJAFQgIAGgXAAIiaAAQgWAAgIgGQgIgFAAgOQAAgJAGgIQAHgGAJAAIAQAAQAKAAAFgLQADgGAAgbIAAh8IgBgeQAAgHgDgEQgHgHgXAAIh0AAQgXAAgGAGQgFAHAAAdIAACCQAAAYACAJQAFALALAAIAQAAQAJAAAGAGQAGAIAAAKQAAAOgIAEQgIAGgVAAIiaAAQgWAAgJgGQgIgFAAgOQAAgJAGgIQAHgGAJAAIARAAQAEgBAFgDQAEgCABgFQADgGAAgbIAAl9QAAgwgkAEQgLABgHAKQgIAIgGAWIiHGzQgJAfgKALQgLALgTAAQgTAAgLgJg");
	this.shape_12.setTransform(-20,-9.9,0.268,0.268);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AihEbQgWAAgIgFQgIgFAAgOQAAgKAGgHQAGgGAJAAIARAAQAEAAAEgDQAEgEACgEQADgIAAgXIAAl/QAAgZgDgJQgDgLgLABIgRAAQgKgBgGgGQgHgHAAgLQAAgNAJgGQAJgFAWAAICcAAQAWAAAJAFQAJAGAAANQAAALgGAHQgHAGgJABIgSAAQgOgBgDALQgDAGAAAcIAAFjQAAAdACAJQACAJAIAFQAGAEALACQALACAagBIAwAAQAvAAAPgfIAIgPQAIgQAPgBQAMAAAFAJQAFAJgEAQIgNBCQgEAVgaAAg");
	this.shape_13.setTransform(18.6,-10,0.268,0.268);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AjREWQgIgGAAgOQAAgJAGgHQAGgGAJAAIARAAQAEAAAEgEQAEgDABgEQAEgIAAgaIAAl7QAAgZgEgIQgBgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgKQAAgNAJgGQAIgFAWAAIFSAAQAZAAAFAVIAMA7QADAQgFAJQgFAIgMAAQgPAAgGgNQgDgCgGgQQgGgQgPgFQgMgEggAAIhQAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAEADAeAAIAmAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAIgOAAQgTAAgEgWIAAgFQgCgNgIgDQgHgEgbAAIgmAAQgeAAgEAEQgIAFAAAZIAABsQAAAiADALQADALAKAEQAPAFAiAAIBVAAQAvAAAPgfIAHgQQAIgQAPAAQAMAAAFAJQAFAJgDAQIgNBCQgDALgHAFQgHAFgOAAIlhAAQgWAAgIgFg");
	this.shape_14.setTransform(30.7,-10,0.268,0.268);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0C6E47").s().p("AqoZNQk7iFjyjyQjyjziFk6QiJlFAAljQAAlkCJlFQCFk6DyjzQDzjyE6iFQFFiJFjAAQFkAAFFCJQE6CFDyDyQDyDzCGE6QCJFFAAFkQAAFjiJFFQiGE6jyDzQjyDyk6CFQlFCJlkAAQljAAlFiJg");
	this.shape_15.setTransform(0,0,0.268,0.268);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.greenlogo, new cjs.Rectangle(-46.9,-46.9,93.9,93.9), null);


(lib.cookietopright = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.seventeentoprightcookie();
	this.instance.parent = this;
	this.instance.setTransform(-27.5,-45.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.cookietopright, new cjs.Rectangle(-27.5,-45.5,55,91), null);


(lib.cookietopleft = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.seventeentopleft();
	this.instance.parent = this;
	this.instance.setTransform(-20,-47);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.cookietopleft, new cjs.Rectangle(-20,-47,40,94), null);


(lib.seventeenrollover = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_11 = function() {
		this.stop();
	}
	this.frame_23 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(11).call(this.frame_11).wait(12).call(this.frame_23).wait(7));

	// cta-rollover
	this.instance = new lib.seventeenvidrollover();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:1},9).wait(2).to({alpha:0},10).wait(8));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-64.5,-80.7,129,33.5);


// stage content:
(lib.wideskyscraperfourteenupdatedcta = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_44 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		
		console.log("this frame works");
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_398 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(44).call(this.frame_44).wait(354).call(this.frame_398).wait(6));

	// button
	this.btn_main = new lib.mainbutton();
	this.btn_main.parent = this;
	this.btn_main.setTransform(82.2,302,0.797,0.919,0,0,0,0.1,0.4);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.mainbutton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(404));

	// grey-rectangle
	this.instance = new lib.greyrectangle();
	this.instance.parent = this;
	this.instance.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(404));

	// fade-from-white
	this.instance_1 = new lib.whiterectanglefade();
	this.instance_1.parent = this;
	this.instance_1.setTransform(91,300.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:0},9).wait(395));

	// kale-logo
	this.instance_2 = new lib.greenlogo();
	this.instance_2.parent = this;
	this.instance_2.setTransform(80,36.9);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({scaleX:0.02,scaleY:0.02},0).to({scaleX:1.08,scaleY:1.08,alpha:1},6,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},7,cjs.Ease.get(1)).wait(382));

	// get-the-party-started
	this.instance_3 = new lib.partystarted();
	this.instance_3.parent = this;
	this.instance_3.setTransform(80,177.2);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(216).to({alpha:1},10).wait(178));

	// holiday-tips-recipes-more
	this.instance_4 = new lib.tipsrecipesmore();
	this.instance_4.parent = this;
	this.instance_4.setTransform(80,243.1);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(216).to({alpha:1},10).wait(178));

	// holiday-hosting-tips
	this.instance_5 = new lib.holidayhostingtips();
	this.instance_5.parent = this;
	this.instance_5.setTransform(80.3,214.9);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(86).to({alpha:1},10).wait(50).to({alpha:0},5).wait(253));

	// sweet-inspiration
	this.instance_6 = new lib.sweetinspiration();
	this.instance_6.parent = this;
	this.instance_6.setTransform(80,214.9);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(146).to({alpha:1},10).wait(50).to({alpha:0},5).wait(193));

	// party-ready-recipes
	this.instance_7 = new lib.partyreadyrecipes();
	this.instance_7.parent = this;
	this.instance_7.setTransform(80,214.9);
	this.instance_7.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(34).to({alpha:1},10).wait(42).to({alpha:0},5).wait(313));

	// shop-now
	this.instance_8 = new lib.seventeenordernow();
	this.instance_8.parent = this;
	this.instance_8.setTransform(80,383);
	this.instance_8.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(46).to({alpha:1},10).wait(348));

	// cta-rollover
	this.cta_rollover = new lib.seventeenrollover();
	this.cta_rollover.parent = this;
	this.cta_rollover.setTransform(80,382.8);
	this.cta_rollover.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.cta_rollover).wait(46).to({alpha:1},10).wait(348));

	// cta-rectangle
	this.instance_9 = new lib.seventeenrectangle();
	this.instance_9.parent = this;
	this.instance_9.setTransform(80,382.8);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(46).to({alpha:1},10).wait(348));

	// cookie-top-right
	this.instance_10 = new lib.cookietopright();
	this.instance_10.parent = this;
	this.instance_10.setTransform(132.5,45.5);
	this.instance_10.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(9).to({alpha:1},10).wait(385));

	// cookie-top-left
	this.instance_11 = new lib.cookietopleft();
	this.instance_11.parent = this;
	this.instance_11.setTransform(20,110.5);
	this.instance_11.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(14).to({alpha:1},10).wait(380));

	// pie-bottom-left
	this.instance_12 = new lib.seventeenpiebottomleft();
	this.instance_12.parent = this;
	this.instance_12.setTransform(51.5,394);
	this.instance_12.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(19).to({alpha:1},10).wait(375));

	// bottom-right
	this.instance_13 = new lib.seventeenbottomright_1();
	this.instance_13.parent = this;
	this.instance_13.setTransform(86.5,535);
	this.instance_13.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(24).to({alpha:1},10).wait(370));

	// table
	this.instance_14 = new lib.seventeentable_1();
	this.instance_14.parent = this;
	this.instance_14.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(404));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(68,274,206.1,652.2);
// library properties:
lib.properties = {
	id: '85088BD5353243C8B4895C262600CED3',
	width: 160,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/index_atlas_.png", id:"index_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['85088BD5353243C8B4895C262600CED3'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;